services:
  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: "${NGINX_DOCKER_IMAGE_NAME}"
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${NGINX_EXTERNAL_PORT_FOR_PORT_80}:80"
      - "${NGINX_EXTERNAL_PORT_FOR_PORT_443}:443"
    restart: ${NGINX_CONTAINER_RESTART}
    volumes:
      - "${NGINX_CONFIG_PATH}:/etc/nginx:ro"
      - "${NGINX_HTML_PATH}:/usr/share/nginx/html:ro"
      - "${LETSENCRYPT_PATH}:/etc/letsencrypt:ro"
      - "${LOG_ABSOLUTE_PATH}:/var/log/nginx"
    healthcheck:
      test: ["CMD", "${NGINX_HEALTHCHECK_TEST}"]
      interval: "${NGINX_HEALTHCHECK_INTERVAL}"
      timeout: "${NGINX_HEALTHCHECK_TIMEOUT}"
      retries: "${NGINX_HEALTHCHECK_RETRIES}"

  certbot:
    container_name: "${CERTBOT_CONTAINER_NAME}"
    image: "${CERTBOT_DOCKER_IMAGE_NAME}"
    env_file:
      - "${ENV_FILE}"
    volumes:
      - "${LETSENCRYPT_PATH}:/etc/letsencrypt"
      - "${NGINX_HTML_PATH}:/usr/share/nginx/html"
      - "${LOG_ABSOLUTE_PATH}:/var/log/letsencrypt/"
    restart: "${CERTBOT_CONTAINER_RESTART}"