services:
  nginx:
    container_name: "${NGINX_CONTAINER_NAME}"
    image: "${NGINX_DOCKER_IMAGE_NAME}"
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${NGINX_EXTERNAL_PORT_FOR_PORT_80}:80"
      - "${NGINX_EXTERNAL_PORT_FOR_PORT_443}:443"
    restart: ${NGINX_CONTAINER_RESTART}
    volumes:
      - "${MOUNT_PATH_FOR_NGINX_CONF}:/etc/nginx/nginx.conf:ro"
      - "${MOUNT_PATH_FOR_COMMON_PROXY_CONF}:/etc/nginx/common_proxy.conf:ro"
      - "${MOUNT_PATH_FOR_SITES_AVAILABLE}:/etc/nginx/sites-available:ro"
      - "${MOUNT_PATH_FOR_SITES_ENABLED}:/etc/nginx/sites-enabled:ro"
      - "${MOUNT_PATH_FOR_HTML}:/usr/share/nginx/html:ro"
      - "${MOUNT_PATH_FOR_LETSENCRYPT}:/etc/letsencrypt:ro"
    healthcheck:
      test: ["CMD", "${HEALTHCHECK_TEST}"]
      interval: "${HEALTHCHECK_INTERVAL}"
      timeout: "${HEALTHCHECK_TIMEOUT}"
      retries: "${HEALTHCHECK_RETRIES}"

  certbot:
    container_name: "${CERTBOT_CONTAINER_NAME}"
    image: "${CERTBOT_DOCKER_IMAGE_NAME}"
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${CERTBOT_EXTERNAL_PORT_FOR_PORT_80}:80"
    volumes:
      - "${MOUNT_PATH_FOR_LETSENCRYPT}:/etc/letsencrypt"
      - "${MOUNT_PATH_FOR_HTML}:/usr/share/nginx/html"
      - "${MOUNT_PATH_FOR_LETSENCRYPT_LOG}:/var/log/letsencrypt/"
    restart: "${CERTBOT_CONTAINER_RESTART}"